version: "3"

services:
  qualix:
    build: .docker
    container_name: 'qualix-app'
    ports:
      - '80:80'
    depends_on:
      - db
      - node
    volumes:
      - .:/var/www
      - ./public/.htaccess.docker:/var/www/public/.htaccess

  db:
    image: mariadb:10.3
    container_name: 'qualix-db'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=qualix
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=qualix
      - MYSQL_PASSWORD=qualix
    ports:
      - '3306:3306'

  mail:
    image: schickling/mailcatcher:latest
    container_name: 'qualix-mail'
    ports:
      - '1080:1080'

  node:
    image: node:14
    container_name: 'qualix-npm'
    working_dir: '/app'
    volumes:
      - .:/app
    command: bash -c "npm install && npm run watch"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'qualix-phpmyadmin'
    depends_on:
      - db
    ports:
      - '8081:80'

  e2e:
    build:
      context: .docker
      dockerfile: Dockerfile.cypress
    working_dir: /e2e
    environment:
      - DISPLAY
      - APP_BASE_URL=http://qualix
      - CYPRESS_PROJECT=.
    volumes:
      - .:/e2e
      - ./.docker/cypress-entrypoint.sh:/bin/entrypoint.sh
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      - qualix
      - e2e-mocks
    entrypoint:
      - /bin/entrypoint.sh
    command: []

  e2e-mocks:
    image: mockserver/mockserver
    ports:
      - '1090:1080'

  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
